# Generated by Django 4.1.1 on 2022-09-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='Memo'),
        ),
    ]
